#!/usr/bin/perl

use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/site-lib";
use CloudForecast::Gearman;
use CloudForecast::ConfigLoader;
use Getopt::Long;

my $root_dir = $FindBin::Bin;
my $config_yaml = $root_dir . '/cloudforecast.yaml';
my $server_list_yaml = $root_dir . '/server_list.yaml';

my $max_workers            = 4;
my $max_requests_per_child = 100;

GetOptions(
    'c|config=s' => \$config_yaml,
    'l|server-list=s' => \$server_list_yaml,
    'max-workers=i'   => \$max_workers,
    'max-request-per-child=i' => \$max_requests_per_child,
);

die 'config not found' unless $config_yaml;
die 'server_list not found' unless $server_list_yaml;

my $configloader = CloudForecast::ConfigLoader->new({
    root_dir => $root_dir,
    global_config => $config_yaml,
    server_list => $server_list_yaml,
});
$configloader->load_all();
my $global_config = $configloader->global_config;

die 'gearman is disabled' unless $global_config->{gearman_enable};


my $gearman = CloudForecast::Gearman->new({
    host => $global_config->{gearman_server}->{host},
    port => $global_config->{gearman_server}->{port},
});

$gearman->fetcher_worker($global_config, $max_workers, $max_requests_per_child);

