#!/usr/bin/perl

use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/site-lib";
use CloudForecast::Gearman::Worker;
use Getopt::Long;

my $root_dir = $FindBin::Bin;
my $config_yaml = $root_dir . '/cloudforecast.yaml';

my $max_workers            = 2;
my $max_requests_per_child = 100;
my $max_execution_time = 60;
my $restarter = 0;

GetOptions(
    'c|config=s' => \$config_yaml,
    'r|restarter' => \$restarter,
    'max-workers=i'   => \$max_workers,
    'max-request-per-child=i' => \$max_requests_per_child,
    'max-exection-time=i' => \$max_execution_time,
);

die 'config not found' unless $config_yaml;

my $gearman = CloudForecast::Gearman::Worker->new({
    root_dir => $root_dir,
    global_config => $config_yaml,
    restarter => $restarter,
    max_workers => $max_workers,
    max_requests_per_child => $max_requests_per_child,
    max_execution_time => $max_execution_time,
});

$gearman->updater_worker();





