#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/extlib/lib/perl5";
use local::lib "$FindBin::Bin/extlib";
use lib "$FindBin::Bin/site-lib";
use CloudForecast::Web::Server;
use Getopt::Long;

my $root_dir = $FindBin::Bin;
my $config = $root_dir . '/cloudforecast.yaml';
my $server_list = $root_dir .'/server_list.yaml';
my $restarter = 0;
my $port = 5000;

GetOptions(
    'port=s' => \$port,
    'r|restarter' => \$restarter,
    'c|config=s' => \$config,
    'l|server-list=s' => \$server_list,
);

die 'config not found' unless $config;
die 'server_list not found' unless $server_list;

CloudForecast::Web::Server->new({
    port => $port,
    restarter => $restarter,
    root_dir => $root_dir,
    global_config => $config,
    server_list => $server_list,
})->run;
